2021-04-29 18:53:40 | repeat_transfer.R --------------------------------------- 
Experiment: 
  id             created output_directory exp_name n_plates
1 13 2021-04-17 12:24:39  20210417_output   output        6
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
  [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [49]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [97]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[109]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[121]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[133]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[145]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
Warning messages:
1: In file.rename(from = str_c(old_path, "/", pickolo_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/pickolo/strainCheckPlates/t10_P0_A_2021042733.jpg' to 'experiments/20210417_output/pickolo/run1/strainCheckPlates/t10_P0_A_2021042733.jpg', reason 'The system cannot find the path specified'
2: In file.rename(from = str_c(old_path, "/", pickolo_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/pickolo/strainCheckPlates/t10_P0_AB_2021042735.jpg' to 'experiments/20210417_output/pickolo/run1/strainCheckPlates/t10_P0_AB_2021042735.jpg', reason 'The system cannot find the path specified'
3: In file.rename(from = str_c(old_path, "/", pickolo_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/pickolo/strainCheckPlates/t10_P0_B_2021042734.jpg' to 'experiments/20210417_output/pickolo/run1/strainCheckPlates/t10_P0_B_2021042734.jpg', reason 'The system cannot find the path specified'
4: In file.rename(from = str_c(old_path, "/", pickolo_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/pickolo/strainCheckPlates/t10_P0_N_2021042732.jpg' to 'experiments/20210417_output/pickolo/run1/strainCheckPlates/t10_P0_N_2021042732.jpg', reason 'The system cannot find the path specified'
[1] TRUE TRUE TRUE TRUE TRUE
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
repeating transfer:
   n run             created     type
1 12   2 2021-04-29 18:53:40 transfer
2021-04-29 18:53:40 | repeat_transfer.R done.---------------------------------- 

2021-04-29 19:05:26 | repeat_transfer.R --------------------------------------- 
Experiment: 
  id             created output_directory exp_name n_plates
1 13 2021-04-17 12:24:39  20210417_output   output        6
[1] FALSE
Warning message:
In file.rename(from = str_c(old_path, "/", od_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/OD/xml/' to 'experiments/20210417_output/OD/xml/run2/', reason 'The process cannot access the file because it is being used by another process'
  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
There were 50 or more warnings (use warnings() to see the first 50)
[1] FALSE
Warning message:
In file.rename(from = str_c(old_path, "/", plate_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/platefiles/' to 'experiments/20210417_output/platefiles/run2/', reason 'The process cannot access the file because it is being used by another process'
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
repeating transfer:
   n run             created     type
1 12   3 2021-04-29 19:05:26 transfer
2021-04-29 19:05:36 | repeat_transfer.R done.---------------------------------- 

2021-04-29 19:09:04 | repeat_transfer.R --------------------------------------- 
Experiment: 
  id             created output_directory exp_name n_plates
1 13 2021-04-17 12:24:39  20210417_output   output        6
[1] FALSE
Warning message:
In file.rename(from = str_c(old_path, "/", od_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/OD/xml/' to 'experiments/20210417_output/OD/xml/run3/', reason 'The process cannot access the file because it is being used by another process'
  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
There were 50 or more warnings (use warnings() to see the first 50)
[1] FALSE
Warning message:
In file.rename(from = str_c(old_path, "/", plate_files), to = str_c(new_path,  :
  cannot rename file 'experiments/20210417_output/platefiles/' to 'experiments/20210417_output/platefiles/run3/', reason 'The process cannot access the file because it is being used by another process'
Warning message:
`data_frame()` was deprecated in tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
repeating transfer:
   n run             created     type
1 12   4 2021-04-29 19:09:04 transfer
2021-04-29 19:09:15 | repeat_transfer.R done.---------------------------------- 

